//! Rendering the aggregate into the deterministic `LESSONS.md` markdown body.

use crate::UNCATEGORIZED;
use crate::aggregate::{AggResult, Bucket, ContestedEntry, Correction, DeadEnd, SourceEntry};

/// Append one bucket's rendered sections to `out`.
fn render_bucket(
    out: &mut Vec<String>,
    preferred: &[SourceEntry],
    tentative: &[SourceEntry],
    contested: &[ContestedEntry],
    dead_ends: &[DeadEnd],
    corrections: &[Correction],
    k: usize,
) {
    if !preferred.is_empty() {
        out.push(format!(
            "**Preferred sources** — corroborated by ≥{k} useful results; start here."
        ));
        out.push(String::new());
        for e in preferred {
            out.push(format!("- `{}` ({}× useful)", e.node, e.n));
        }
        out.push(String::new());
    }
    if !tentative.is_empty() {
        out.push(format!(
            "**Tentative** — useful in fewer than {k} results; verify before relying."
        ));
        out.push(String::new());
        for e in tentative {
            out.push(format!("- `{}` ({}× useful)", e.node, e.n));
        }
        out.push(String::new());
    }
    if !contested.is_empty() {
        out.push("**Contested** — mixed signals; recency decides.".to_string());
        out.push(String::new());
        for e in contested {
            let day: String = e.last.chars().take(10).collect();
            let verdict = if e.verdict == "even" {
                "evenly split".to_string()
            } else {
                format!("recency leans **{}**", e.verdict)
            };
            let suffix = if day.is_empty() {
                String::new()
            } else {
                format!(" (latest {day})")
            };
            out.push(format!(
                "- `{}` — {}× useful, {}× dead end/corrected → {verdict}{suffix}",
                e.node, e.pos, e.neg
            ));
        }
        out.push(String::new());
    }
    if !dead_ends.is_empty() {
        out.push("**Known dead ends** — led nowhere; don't re-derive.".to_string());
        out.push(String::new());
        for d in dead_ends {
            let nodes = d
                .nodes
                .iter()
                .map(|n| format!("`{n}`"))
                .collect::<Vec<_>>()
                .join(", ");
            let suffix = if nodes.is_empty() {
                String::new()
            } else {
                format!(" — {nodes}")
            };
            out.push(format!("- \"{}\"{suffix}", d.question));
        }
        out.push(String::new());
    }
    if !corrections.is_empty() {
        out.push("**Corrections** — do these differently.".to_string());
        out.push(String::new());
        for c in corrections {
            out.push(format!("- \"{}\" → {}", c.question, c.correction));
        }
        out.push(String::new());
    }
    if preferred.is_empty()
        && tentative.is_empty()
        && contested.is_empty()
        && dead_ends.is_empty()
        && corrections.is_empty()
    {
        out.push("_No marked outcomes yet._".to_string());
        out.push(String::new());
    }
}

/// Render the aggregate into the deterministic `LESSONS.md` markdown body.
#[must_use]
pub fn render_lessons_md(agg: &AggResult) -> String {
    let c = &agg.counts;
    let k = agg.min_corroboration;
    let memory_word = if agg.total == 1 { "memory" } else { "memories" };
    let mut out: Vec<String> = vec![
        "# Lessons".to_string(),
        String::new(),
        format!(
            "_Auto-generated by `graphify reflect` from {} session {memory_word} in \
             graphify-out/memory/. Deterministic; no LLM. Use for orientation — verify \
             before relying, and revisit dead ends if the code has changed since._",
            agg.total
        ),
        String::new(),
        "## Summary".to_string(),
        String::new(),
        format!(
            "- {} useful · {} dead ends · {} corrected · {} unmarked",
            c.useful, c.dead_end, c.corrected, c.unmarked
        ),
        String::new(),
        "## Lessons".to_string(),
        String::new(),
    ];
    render_bucket(
        &mut out,
        &agg.preferred,
        &agg.tentative,
        &agg.contested,
        &agg.dead_ends,
        &agg.corrections,
        k,
    );

    if !agg.by_community.is_empty() {
        out.push("## By topic".to_string());
        out.push(String::new());
        // Uncategorized sorts last; everything else alphabetically.
        let mut labels: Vec<&String> = agg.by_community.keys().collect();
        labels.sort_by(|a, b| {
            let ka = (usize::from(a.as_str() == UNCATEGORIZED), a.as_str());
            let kb = (usize::from(b.as_str() == UNCATEGORIZED), b.as_str());
            ka.cmp(&kb)
        });
        for label in labels {
            out.push(format!("### {label}"));
            out.push(String::new());
            let b: &Bucket = &agg.by_community[label];
            render_bucket(
                &mut out,
                &b.preferred,
                &b.tentative,
                &b.contested,
                &b.dead_ends,
                &b.corrections,
                k,
            );
        }
    }

    // Single trailing newline, no trailing whitespace lines.
    format!("{}\n", out.join("\n").trim_end_matches('\n'))
}
