//! Python rationale extraction (docstrings + RATIONALE-prefixed comments).

use std::path::Path;

use crate::types::FileResult;

const RATIONALE_PREFIXES: &[&str] = &[
    "# NOTE:",
    "# IMPORTANT:",
    "# HACK:",
    "# WHY:",
    "# RATIONALE:",
    "# TODO:",
    "# FIXME:",
];

/// Augment a Python extraction result with rationale nodes sourced from docstrings and comments.
///
/// Walks the file's AST for module, class, and function docstrings (> 20 chars) and scans
/// source lines for `RATIONALE_PREFIXES` comments. Each rationale becomes a node of
/// `file_type = "rationale"` connected via a `rationale_for` edge to the containing entity.
/// Auto-generated files (migrations, protobuf, Alembic) are silently skipped.
/// Mirrors Python `_extract_rationale`.
pub(super) fn extract_python_rationale(path: &Path, result: &mut FileResult) {
    use crate::ids::{file_stem, make_id, make_id1};
    use crate::types::{Edge, Node};
    use std::collections::HashSet;
    use tree_sitter::Parser;

    let Ok(source) = std::fs::read(path) else {
        return;
    };

    let mut parser = Parser::new();
    if parser
        .set_language(&tree_sitter_python::LANGUAGE.into())
        .is_err()
    {
        return;
    }
    let Some(tree) = parser.parse(&source, None) else {
        return;
    };

    let stem = file_stem(path);
    let str_path = path.to_string_lossy().into_owned();
    let file_nid = make_id1(&str_path);
    let mut seen_ids: HashSet<String> = result.nodes.iter().map(|n| n.id.clone()).collect();

    let add_rationale = |text: &str,
                         line: u32,
                         parent_nid: &str,
                         seen: &mut HashSet<String>,
                         nodes: &mut Vec<Node>,
                         edges: &mut Vec<Edge>| {
        let label: String = text
            .chars()
            .take(80)
            .collect::<String>()
            .replace("\r\n", " ")
            .replace(['\r', '\n'], " ")
            .trim()
            .to_string();
        let rid = make_id(&[&stem, "rationale", &line.to_string()]);
        if seen.insert(rid.clone()) {
            nodes.push(Node {
                id: rid.clone(),
                label,
                file_type: "rationale".to_string(),
                source_file: str_path.clone(),
                source_location: Some(format!("L{line}")),
                metadata: None,
                origin_file: None,
            });
        }
        edges.push(Edge {
            external: false,
            source: rid,
            target: parent_nid.to_string(),
            relation: "rationale_for".to_string(),
            confidence: "EXTRACTED".to_string(),
            source_file: str_path.clone(),
            source_location: Some(format!("L{line}")),
            weight: 1.0,
            context: None,
            confidence_score: None,
        });
    };

    // Module-level docstring — skipped for auto-generated files (Alembic /
    // Django migrations, protobuf stubs) whose module docstrings are revision
    // annotations, not architectural rationale. Class/function docstrings and
    // `# NOTE:`-style comments below are still extracted (Python parity).
    let root = tree.root_node();
    if !is_autogenerated_python(&source)
        && let Some((doc, line)) = get_docstring(root, &source)
    {
        add_rationale(
            &doc,
            line,
            &file_nid,
            &mut seen_ids,
            &mut result.nodes,
            &mut result.edges,
        );
    }

    // Walk class/function docstrings
    {
        let mut doc_ctx = DocstringWalkCtx {
            stem: &stem,
            file_nid: &file_nid,
            seen_ids: &mut seen_ids,
            nodes: &mut result.nodes,
            edges: &mut result.edges,
            add_rationale: &add_rationale,
        };
        walk_docstrings(&mut doc_ctx, root, &file_nid, &source);
    }

    // Rationale comments
    let source_text = String::from_utf8_lossy(&source).into_owned();
    for (lineno, line_text) in source_text.lines().enumerate() {
        let stripped = line_text.trim();
        if RATIONALE_PREFIXES.iter().any(|p| stripped.starts_with(p)) {
            add_rationale(
                stripped,
                u32::try_from(lineno).unwrap_or(u32::MAX).saturating_add(1),
                &file_nid,
                &mut seen_ids,
                &mut result.nodes,
                &mut result.edges,
            );
        }
    }
}

/// Return `true` when the Python source is auto-generated and should not have rationale extracted.
///
/// Checks the first 2048 bytes for `DO NOT EDIT`, `@generated`, or protobuf markers, and also
/// detects Alembic/Flask-Migrate migration files and Django migration classes. Mirrors Python
/// `_is_autogenerated`.
fn is_autogenerated_python(source: &[u8]) -> bool {
    let head = String::from_utf8_lossy(&source[..source.len().min(2048)]).into_owned();
    if head.contains("DO NOT EDIT")
        || head.contains("@generated")
        || head.contains("Generated by the protocol buffer")
    {
        return true;
    }
    // Alembic / Flask-Migrate
    if head.contains("def upgrade(")
        && head.contains("down_revision")
        && head.lines().any(|l| {
            let t = l.trim();
            t.starts_with("revision") && (t.contains(':') || t.contains('='))
        })
    {
        return true;
    }
    // Django migrations
    if head.contains("class Migration(migrations.Migration)") && head.contains("operations") {
        return true;
    }
    false
}

/// Extract the first triple-quoted docstring from a Python AST node's first child.
///
/// Looks for an `expression_statement` as the first child containing a `string` or
/// `concatenated_string` node; returns `(cleaned_text, line_number)` when the cleaned text
/// exceeds 20 characters (too-short strings are likely not real docstrings).
fn get_docstring(node: tree_sitter::Node<'_>, source: &[u8]) -> Option<(String, u32)> {
    let mut cur = node.walk();
    if !cur.goto_first_child() {
        return None;
    }
    let child = cur.node();
    if child.kind() == "expression_statement" {
        let mut ecur = child.walk();
        if ecur.goto_first_child() {
            loop {
                let sub = ecur.node();
                if matches!(sub.kind(), "string" | "concatenated_string") {
                    let text = String::from_utf8_lossy(&source[sub.start_byte()..sub.end_byte()])
                        .into_owned();
                    let clean = text
                        .trim_matches('"')
                        .trim_matches('\'')
                        .trim_start_matches("\"\"\"")
                        .trim_end_matches("\"\"\"")
                        .trim_start_matches("'''")
                        .trim_end_matches("'''")
                        .trim()
                        .to_string();
                    if clean.len() > 20 {
                        let row = child.start_position().row;
                        return Some((
                            clean,
                            u32::try_from(row).unwrap_or(u32::MAX).saturating_add(1),
                        ));
                    }
                }
                if !ecur.goto_next_sibling() {
                    break;
                }
            }
        }
    }
    None
}

/// Recursively walk a Python AST node extracting docstrings from class and function bodies.
///
/// For `class_definition` nodes, extracts the class body docstring and recurses into methods.
/// For `function_definition` nodes, extracts the function body docstring and stops recursing.
/// All other nodes are traversed without emitting rationale. Called by `extract_python_rationale`.
/// Shared state threaded through every [`walk_docstrings`] recursion.
struct DocstringWalkCtx<'a, F>
where
    F: Fn(
        &str,
        u32,
        &str,
        &mut std::collections::HashSet<String>,
        &mut Vec<crate::types::Node>,
        &mut Vec<crate::types::Edge>,
    ),
{
    stem: &'a str,
    file_nid: &'a str,
    seen_ids: &'a mut std::collections::HashSet<String>,
    nodes: &'a mut Vec<crate::types::Node>,
    edges: &'a mut Vec<crate::types::Edge>,
    add_rationale: &'a F,
}

fn walk_docstrings<F>(
    ctx: &mut DocstringWalkCtx<'_, F>,
    node: tree_sitter::Node<'_>,
    parent_nid: &str,
    source: &[u8],
) where
    F: Fn(
        &str,
        u32,
        &str,
        &mut std::collections::HashSet<String>,
        &mut Vec<crate::types::Node>,
        &mut Vec<crate::types::Edge>,
    ),
{
    use crate::ids::make_id;
    let t = node.kind();
    if t == "class_definition" {
        if let Some(name_node) = node.child_by_field_name("name") {
            let class_name =
                String::from_utf8_lossy(&source[name_node.start_byte()..name_node.end_byte()])
                    .into_owned();
            let nid = make_id(&[ctx.stem, &class_name]);
            if let Some(body) = node.child_by_field_name("body") {
                if let Some((doc, line)) = get_docstring(body, source) {
                    (ctx.add_rationale)(&doc, line, &nid, ctx.seen_ids, ctx.nodes, ctx.edges);
                }
                let mut cur = body.walk();
                if cur.goto_first_child() {
                    loop {
                        let child = cur.node();
                        walk_docstrings(ctx, child, &nid, source);
                        if !cur.goto_next_sibling() {
                            break;
                        }
                    }
                }
            }
        }
        return;
    }
    if t == "function_definition" {
        if let Some(name_node) = node.child_by_field_name("name") {
            let func_name =
                String::from_utf8_lossy(&source[name_node.start_byte()..name_node.end_byte()])
                    .into_owned();
            let nid = if parent_nid == ctx.file_nid {
                make_id(&[ctx.stem, &func_name])
            } else {
                make_id(&[parent_nid, &func_name])
            };
            if let Some(body) = node.child_by_field_name("body")
                && let Some((doc, line)) = get_docstring(body, source)
            {
                (ctx.add_rationale)(&doc, line, &nid, ctx.seen_ids, ctx.nodes, ctx.edges);
            }
        }
        return;
    }
    let mut cur = node.walk();
    if cur.goto_first_child() {
        loop {
            let child = cur.node();
            walk_docstrings(ctx, child, parent_nid, source);
            if !cur.goto_next_sibling() {
                break;
            }
        }
    }
}
