//! Neo4j Cypher export — `to_cypher`.
//!
//! Mirrors Python `to_cypher`, `_cypher_escape`, `_cypher_label`
//! from `graphify-py/graphify/export.py`.

use std::path::Path;

use graphify_build::Graph;
use regex::Regex;

use crate::ExportError;

/// Escape a string for safe embedding in a Cypher single-quoted literal.
///
/// Mirrors Python `_cypher_escape`.
#[must_use]
pub fn cypher_escape(s: &str) -> String {
    // Drop NUL and other C0 control chars except tab
    let s: String = s.chars().filter(|&c| c >= ' ' || c == '\t').collect();
    s.replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

// Restrict identifier-position values (labels and relationship types are NOT
// quoted in Cypher and so cannot be safely escaped — they must be allowlisted).
static CYPHER_IDENT_RE: std::sync::LazyLock<Regex> = std::sync::LazyLock::new(|| {
    // Known-good literal pattern — panic here would be a programmer error.
    #[allow(clippy::unwrap_used)]
    Regex::new(r"[^A-Za-z0-9_]").unwrap()
});

/// Sanitise a value used in identifier position (node label / rel type).
///
/// Strips everything except `[A-Za-z0-9_]`; requires the result to start
/// with a letter. Otherwise falls back to `fallback`.
///
/// Mirrors Python `_cypher_label`.
#[must_use]
pub fn cypher_label(raw: &str, fallback: &str) -> String {
    let cleaned = CYPHER_IDENT_RE.replace_all(raw, "");
    if cleaned.is_empty() || !cleaned.starts_with(|c: char| c.is_alphabetic()) {
        return fallback.to_string();
    }
    cleaned.into_owned()
}

/// Export graph as a Neo4j Cypher import script.
///
/// Mirrors Python `to_cypher`.
///
/// # Errors
///
/// Returns [`ExportError::Io`] on file-write failure.
pub fn to_cypher(graph: &Graph, output_path: &Path) -> Result<(), ExportError> {
    let mut lines: Vec<String> = vec![
        "// Neo4j Cypher import - generated by /graphify".to_string(),
        String::new(),
    ];

    for (node_id, data) in graph.nodes() {
        let label = data
            .get("label")
            .and_then(serde_json::Value::as_str)
            .unwrap_or(node_id);
        let label_esc = cypher_escape(label);
        let node_id_esc = cypher_escape(node_id);
        let ftype = cypher_label(
            &data
                .get("file_type")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("unknown")
                .to_string()
                .chars()
                .enumerate()
                .map(|(i, c)| {
                    if i == 0 {
                        c.to_uppercase().next().unwrap_or(c)
                    } else {
                        c
                    }
                })
                .collect::<String>(),
            "Entity",
        );
        lines.push(format!(
            "MERGE (n:{ftype} {{id: '{node_id_esc}', label: '{label_esc}'}});"
        ));
    }

    lines.push(String::new());

    for edge in graph.edges() {
        let relation_raw = edge
            .attrs
            .get("relation")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("RELATES_TO");
        let rel = cypher_label(&relation_raw.to_uppercase(), "RELATES_TO");
        let conf = cypher_escape(
            edge.attrs
                .get("confidence")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("EXTRACTED"),
        );
        let u_esc = cypher_escape(&edge.source);
        let v_esc = cypher_escape(&edge.target);
        lines.push(format!(
            "MATCH (a {{id: '{u_esc}'}}), (b {{id: '{v_esc}'}}) \
             MERGE (a)-[:{rel} {{confidence: '{conf}'}}]->(b);"
        ));
    }

    std::fs::write(output_path, lines.join("\n"))?;
    Ok(())
}
