[bans]
allow-wildcard-paths = true
multiple-versions = "allow"
wildcards = "deny"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"
